name: 'Linear PR Title'
description: 'Update PR title to Linear issue {id} {title}'
author: 'novdov'
inputs:
  gh-token: # change this
    required: true
    description: 'Github auth token'
  linear-api-key:
    required: true
    description: 'Linear API key'
  branch-format:
    required: false
    description: 'Branch format used by Linear Github integration'
runs:
  using: 'node16'
  main: 'dist/index.js'
